DESC employees;

--EX 1
SELECT FIRST_NAME || ' ' || LAST_NAME ||'CASTIGA ' || SALARY || ' LUNAR DAR DORESTE ' || SALARY * 3 AS "SALARIU IDEAL" FROM EMPLOYEES;

--EX2
SELECT INITCAP(FIRST_NAME) || ' ' || UPPER(LAST_NAME) || ' ' || LENGTH(LAST_NAME) FROM EMPLOYEES WHERE LAST_NAME LIKE('J%') OR LAST_NAME LIKE('M%') OR LOWER(LAST_NAME) LIKE('--a%');
SELECT UPPER(LAST_NAME) FROM EMPLOYEES WHERE SUBSTR(LAST_NAME, 1, 1) = 'L' OR SUBSTR(LAST_NAME, 1, 1) = 'M' OR LOWER(SUBSTR(LAST_NAME, 3, 1)) = 'a';

--EX3
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE TRIM(BOTH ' ' FROM LOWER(FIRST_NAME)) = 'steven';

--EX4

SELECT EMPLOYEE_ID AS "COD", LAST_NAME AS "NUME", LENGTH(LAST_NAME) AS "LUNGIME", INSTR(LOWER(LAST_NAME), 'a', 1, 1) AS "SUB"
FROM EMPLOYEES 
WHERE LOWER(SUBSTR(LAST_NAME, -1)) = 'e';

--EX5
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE MOD(TRUNC(SYSDATE-HIRE_DATE),7) = 0;

--EX6
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, ROUND(SALARY + 0.15 * SALARY, 2) AS "SALARIU NOU"
FROM EMPLOYEES
WHERE MOD(SALARY, 1000) != 0;

--EX7
SELECT LAST_NAME AS "NUME ANGAJAT", HIRE_DATE AS "DATA ANGAJARII"
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

--EX8
SELECT SYSDATE + 30 "PESTE 30 DE ZILE"
FROM DUAL;

--EX 9
SELECT ROUND(LAST_DAY('02-DEC-2020') - SYSDATE)
FROM DUAL;

--EX 10
SELECT TO_CHAR(SYSDATE + 0.5, 'DD/MM/YYYY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE + 5 * (1 / (24 * 60)), 'DD/MM/YYYY')
FROM DUAL;

--EX 11
SELECT LAST_NAME || ' ' || FIRST_NAME "NUME", HIRE_DATE "DATA ANGAJARII", NEXT_DAY(ADD_MONTHS(HIRE_DATE, 6), 'MONDAY') "ZI NEGOCIERE SALARIU"
FROM EMPLOYEES;

--EX 12
SELECT LAST_NAME || ' ' || FIRST_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE))
FROM EMPLOYEES;

--EX 13
SELECT LAST_NAME, HIRE_DATE, TO_CHAR(HIRE_DATE, 'DAY') "ZI"
FROM EMPLOYEES;

--EX14
SELECT LAST_NAME || ' ' || FIRST_NAME "NUME", NVL(TO_CHAR(COMMISSION_PCT), 'FARA COMISION') "COMISION"
FROM EMPLOYEES
ORDER BY COMISION;

--EX15
SELECT LAST_NAME || ' ' || FIRST_NAME "NUME", SALARY "SALARIU", NVL(TO_CHAR(COMMISSION_PCT), 'FARA COMISION') "COMISION"
FROM EMPLOYEES
WHERE SALARY * (1 + NVL(COMMISSION_PCT, 0)) >= 10000
ORDER BY SALARIU;

--EX 16
SELECT LAST_NAME || ' ' || FIRST_NAME "NUME", JOB_ID, SALARY, 
SALARY * ( 1 + DECODE(JOB_ID, 'IT_PROG', 0.2, 'SA_REP', 0.25, 'SA_MAN', 0.35, 0)) "SALARIU RENEGOCIAT"
FROM EMPLOYEES
ORDER BY "SALARIU RENEGOCIAT";

--EX 17
SELECT LAST_NAME || ' ' || FIRST_NAME "NUME", T2.DEPARTMENT_ID, T2.DEPARTMENT_NAME
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID;

--EX18
SELECT JOB_ID
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE T1.DEPARTMENT_ID = 30;

--EX 19
SELECT T1.LAST_NAME || ' ' || T1.FIRST_NAME "NUME", T2.DEPARTMENT_NAME "NUME DEPARTAMENT", T2.LOCATION_ID "LOCATIE"
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE NVL(COMMISSION_PCT, 0) != 0;

--EX20
SELECT T1.LAST_NAME || ' ' || T1.FIRST_NAME "NUME", T2.DEPARTMENT_NAME "NUME DEPARTAMENT"
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE INSTR(LOWER(LAST_NAME), 'a', 1) != 0 AND INSTR(LOWER(FIRST_NAME), 'a', 1) != 0;

--EX21
SELECT T1.LAST_NAME || ' ' || T1.FIRST_NAME "NUME", T1.JOB_ID "JOBUL", T2.DEPARTMENT_ID "CODUL DEPARTAMENTULUI",
T2.DEPARTMENT_NAME "NUMELE DEPARTAMENTULUI"
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE T2.LOCATION_ID = ( SELECT LOCATION_ID
                         FROM LOCATIONS
                         WHERE CITY LIKE '%Oxford%');
                         
--EX22
SELECT T1.EMPLOYEE_ID "ANG#", T1.LAST_NAME "ANGAJAT", T2.EMPLOYEE_ID "MGR#", T2.LAST_NAME "MANAGER"
FROM EMPLOYEES T1
INNER JOIN EMPLOYEES T2
ON T1.MANAGER_ID = T2.EMPLOYEE_ID;

--EX23
SELECT T1.EMPLOYEE_ID "ANG#", T1.LAST_NAME "ANGAJAT", T2.EMPLOYEE_ID "MGR#", T2.LAST_NAME "MANAGER"
FROM EMPLOYEES T1
LEFT OUTER JOIN EMPLOYEES T2
ON T1.MANAGER_ID = T2.EMPLOYEE_ID;

--EX24
SELECT T1.LAST_NAME || ' ' || T1.FIRST_NAME "NUME ANGAJAT", T1.DEPARTMENT_ID "ID DEPARTAMENT", T2.LAST_NAME || ' ' || T2.FIRST_NAME "NUME COLEG"
FROM EMPLOYEES T1
JOIN EMPLOYEES T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID;

--EX25
SELECT T1.LAST_NAME || ' ' || T1.FIRST_NAME "NUME", T2.JOB_ID, T2.JOB_TITLE, T1.DEPARTMENT_ID, T1.SALARY
FROM EMPLOYEES T1
INNER JOIN JOBS T2
ON T1.JOB_ID = T2.JOB_ID;

--EX26
SELECT LAST_NAME || ' ' || FIRST_NAME "NUME",HIRE_DATE "DATA ANGAJARII"
FROM EMPLOYEES
WHERE HIRE_DATE > ( SELECT HIRE_DATE
                    FROM EMPLOYEES
                    WHERE LAST_NAME = 'Gates');
                    
--EX27
SELECT T1.LAST_NAME || ' ' || T1.FIRST_NAME "ANGAJAT", T1.HIRE_DATE "DATA ANGAJ",
       T2.LAST_NAME || ' ' || T2.FIRST_NAME "MANAGER", T2.HIRE_DATE "DATA MAN"
FROM EMPLOYEES T1
INNER JOIN EMPLOYEES T2
ON T1.MANAGER_ID = T2.EMPLOYEE_ID
WHERE T1.HIRE_DATE < T2.HIRE_DATE;

