#EX1

SELECT LAST_NAME, TO_CHAR(HIRE_DATE, 'DD-MON-YYYY')
FROM EMPLOYEES
WHERE DEPARTMENT_ID = ( SELECT DEPARTMENT_ID
                         FROM EMPLOYEES
                         WHERE LAST_NAME = 'Gates')
    AND INSTR(LOWER(LAST_NAME), 'a') != 0 AND LAST_NAME != 'Gates';
    
#EX2

SELECT T1.EMPLOYEE_ID, T1.LAST_NAME, T1.DEPARTMENT_ID, T2.DEPARTMENT_NAME
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE INSTR(LOWER(T1.LAST_NAME), 't') != 0
ORDER BY T1.LAST_NAME;

#EX3

SELECT T3.LAST_NAME, T3.SALARY, T5.JOB_TITLE, T4.CITY, T6.COUNTRY_NAME
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2 ON T2.MANAGER_ID = T1.EMPLOYEE_ID AND T1.LAST_NAME = 'King'
INNER JOIN EMPLOYEES T3 ON T3.DEPARTMENT_ID = T2.DEPARTMENT_ID
INNER JOIN LOCATIONS T4 ON T4.LOCATION_ID = T2.LOCATION_ID
INNER JOIN JOBS T5 ON T5.JOB_ID = T3.JOB_ID
INNER JOIN COUNTRIES T6 ON T6.COUNTRY_ID = T4.COUNTRY_ID
ORDER BY T3.LAST_NAME;

#EX4

SELECT T2.DEPARTMENT_ID, T2.DEPARTMENT_NAME, T1.LAST_NAME, T3.JOB_TITLE, TO_CHAR(T1.SALARY,'L99G999D99')
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2 ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID AND INSTR(LOWER(DEPARTMENT_NAME), 'ti') != 0
INNER JOIN JOBS T3 ON T1.JOB_ID = T3.JOB_ID
ORDER BY T2.DEPARTMENT_NAME, T1.LAST_NAME;

#EX5

SELECT T1.LAST_NAME, T2.DEPARTMENT_ID, T2.DEPARTMENT_NAME, T3.CITY, T4.JOB_TITLE
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2 ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
INNER JOIN LOCATIONS T3 ON T2.LOCATION_ID = T3.LOCATION_ID AND T3.CITY = 'Oxford'
INNER JOIN JOBS T4 ON T1.JOB_ID = T4.JOB_ID;

#EX6

SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES T1
INNER JOIN (SELECT DEPARTMENT_ID, (MIN(SALARY) + MAX(SALARY))/2 MED_SALARY
            FROM EMPLOYEES
            GROUP BY DEPARTMENT_ID) T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE T1.SALARY > T2.MED_SALARY

#EX7

SELECT T2.LAST_NAME, T1.DEPARTMENT_NAME
FROM DEPARTMENTS T1
RIGHT OUTER JOIN EMPLOYEES T2 USING (DEPARTMENT_ID);

#EX8

SELECT T1.DEPARTMENT_NAME, T2.LAST_NAME
FROM DEPARTMENTS T1
LEFT OUTER JOIN EMPLOYEES T2 USING (DEPARTMENT_ID);

#EX9

SELECT T1.DEPARTMENT_NAME, T2.LAST_NAME
FROM DEPARTMENTS T1
FULL OUTER JOIN EMPLOYEES T2 USING (DEPARTMENT_ID);

#EX10

SELECT DEPARTMENT_ID
FROM DEPARTMENTS 
WHERE INSTR(LOWER(DEPARTMENT_NAME), 're')!=0
UNION
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE 'SA_REP';
#ORDINE CRESCATOARE

#EX11

SELECT DEPARTMENT_ID
FROM DEPARTMENTS 
WHERE INSTR(LOWER(DEPARTMENT_NAME), 're')!=0
UNION ALL
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE 'SA_REP';

#EX12

SELECT DEPARTMENT_ID
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID
FROM EMPLOYEES;

#EX13

SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE INSTR(LOWER(DEPARTMENT_NAME), 're')!=0
INTERSECT
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE 'HR_REP';

#EX14

SELECT T1.EMPLOYEE_ID, T1.JOB_ID, T1.LAST_NAME
FROM EMPLOYEES T1
INNER JOIN (SELECT DEPARTMENT_ID, (MIN(SALARY) + MAX(SALARY))/2 MED_SALARY
            FROM EMPLOYEES
            GROUP BY DEPARTMENT_ID) T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE T1.SALARY >= T2.MED_SALARY OR T1.SALARY > 3000;

#EX15

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE > (SELECT HIRE_DATE
                   FROM EMPLOYEES
                   WHERE LAST_NAME = 'Gates');
                   
#EX16

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
                      FROM EMPLOYEES
                      WHERE LAST_NAME = 'Gates');

#EX17

SELECT T1.LAST_NAME, T1.SALARY
FROM EMPLOYEES T1
INNER JOIN (SELECT EMPLOYEE_ID
            FROM EMPLOYEES
            WHERE MANAGER_ID IS NULL) T2
ON T1.MANAGER_ID = T2.EMPLOYEE_ID;

#EX18

SELECT T1.LAST_NAME, T1.DEPARTMENT_ID, T1.SALARY
FROM EMPLOYEES T1
INNER JOIN (SELECT DEPARTMENT_ID, SALARY
            FROM EMPLOYEES
            WHERE COMMISSION_PCT > 0) T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID AND T1.SALARY = T2.SALARY;

#EX19

SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES T1
INNER JOIN (SELECT DEPARTMENT_ID, (MIN(SALARY) + MAX(SALARY))/2 MED_SALARY
            FROM EMPLOYEES
            GROUP BY DEPARTMENT_ID) T2
ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE T1.SALARY > T2.MED_SALARY

#EX20

SELECT *
FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY
                    FROM EMPLOYEES
                    WHERE JOB_ID LIKE '%CLERK%')
ORDER BY SALARY DESC;

#EX21

SELECT T1.LAST_NAME, T2.DEPARTMENT_NAME, T1.SALARY
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2 ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE COMMISION_PCT = 0 AND MANAGER_ID = (SELECT MANAGER_ID
                                          FROM EMPLOYEES
                                          WHERE COMMISION_PCT > 0);

#EX22

SELECT LAST_NAME, DEPARTMENT_NAME, SALARY, JOB_ID
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2 ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
WHERE 

#EX23

SELECT T1.LAST_NAME, T1.DEPARTMENT_ID, T1.JOB_ID
FROM EMPLOYEES T1
INNER JOIN DEPARTMENTS T2 ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
INNER JOIN LOCATIONS T3 ON T2.LOCATION_ID = T3.LOCATION_ID
WHERE CITY LIKE '%Toronto%';

